# Configuración optimizada para Cloudflare Pages
# Esta configuración está diseñada específicamente para SPAs de React

[build]
  command = "npm run build"
  publish = "dist"
  node_bundler = "esbuild"

[build.environment]
  NODE_VERSION = "20"

# Redirecciones SPA - CRÍTICO para que la navegación funcione correctamente
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
